config/routes.rb
Rails.application.routes.draw do
  resources :toolings
  resources :parts
  devise_for :supplier_users
  devise_for :honda_users
  resources :events
  resources :projects
  resources :maker_layouts
  resources :plants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/cost.rb
class Cost < ApplicationRecord
end

app/models/design_confirm.rb
class DesignConfirm < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/honda_user.rb
class HondaUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/maker_layout.rb
class MakerLayout < ApplicationRecord
end

app/models/maturation_confirm.rb
class MaturationConfirm < ApplicationRecord
end

app/models/part.rb
class Part < ApplicationRecord
end

app/models/plant.rb
class Plant < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/supplier_user.rb
class SupplierUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/tooling.rb
class Tooling < ApplicationRecord
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:part_number, :part_name, :process_1, :process_2, :process_3, :color, :makerlayout_id)
    end
end

app/controllers/toolings_controller.rb
class ToolingsController < ApplicationController
  before_action :set_tooling, only: [:show, :edit, :update, :destroy]

  # GET /toolings
  # GET /toolings.json
  def index
    @toolings = Tooling.all
  end

  # GET /toolings/1
  # GET /toolings/1.json
  def show
  end

  # GET /toolings/new
  def new
    @tooling = Tooling.new
  end

  # GET /toolings/1/edit
  def edit
  end

  # POST /toolings
  # POST /toolings.json
  def create
    @tooling = Tooling.new(tooling_params)

    respond_to do |format|
      if @tooling.save
        format.html { redirect_to @tooling, notice: 'Tooling was successfully created.' }
        format.json { render :show, status: :created, location: @tooling }
      else
        format.html { render :new }
        format.json { render json: @tooling.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /toolings/1
  # PATCH/PUT /toolings/1.json
  def update
    respond_to do |format|
      if @tooling.update(tooling_params)
        format.html { redirect_to @tooling, notice: 'Tooling was successfully updated.' }
        format.json { render :show, status: :ok, location: @tooling }
      else
        format.html { render :edit }
        format.json { render json: @tooling.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toolings/1
  # DELETE /toolings/1.json
  def destroy
    @tooling.destroy
    respond_to do |format|
      format.html { redirect_to toolings_url, notice: 'Tooling was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tooling
      @tooling = Tooling.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tooling_params
      params.require(:tooling).permit(:deliver_to, :part_type, :part_level, :commodity, :tool_source, :go1_go2_lt, :go2_t1_lt, :t1_t2_lt, :t2_t3_lt, :t3_t4_lt, :t4_linetry_lt, :raw_material_lt, :go1_1_target, :go1_1_actual, :go1_1_design_target, :go1_1_correlated, :go1_2_target, :go1_2_actual, :go2_1_actual, :go2_2_target, :go2_2_actual, :go2_2_design_target, :go2_2_correlated, :go2_3_actual, :go1_1_design_number, :go1_2_design_number, :go2_1_design_number, :go2_2_design_number, :go2_3_design_change)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/maker_layouts_helper.rb
module MakerLayoutsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/toolings_helper.rb
module ToolingsHelper
end

app/views/toolings/_form.html.erb
<%= form_with(model: tooling, local: true) do |form| %>
  <% if tooling.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tooling.errors.count, "error") %> prohibited this tooling from being saved:</h2>

      <ul>
      <% tooling.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :deliver_to %>
    <%= form.text_field :deliver_to %>
  </div>

  <div class="field">
    <%= form.label :part_type %>
    <%= form.text_field :part_type %>
  </div>

  <div class="field">
    <%= form.label :part_level %>
    <%= form.text_field :part_level %>
  </div>

  <div class="field">
    <%= form.label :commodity %>
    <%= form.text_field :commodity %>
  </div>

  <div class="field">
    <%= form.label :tool_source %>
    <%= form.text_field :tool_source %>
  </div>

  <div class="field">
    <%= form.label :go1_go2_lt %>
    <%= form.number_field :go1_go2_lt %>
  </div>

  <div class="field">
    <%= form.label :go2_t1_lt %>
    <%= form.number_field :go2_t1_lt %>
  </div>

  <div class="field">
    <%= form.label :t1_t2_lt %>
    <%= form.number_field :t1_t2_lt %>
  </div>

  <div class="field">
    <%= form.label :t2_t3_lt %>
    <%= form.number_field :t2_t3_lt %>
  </div>

  <div class="field">
    <%= form.label :t3_t4_lt %>
    <%= form.number_field :t3_t4_lt %>
  </div>

  <div class="field">
    <%= form.label :t4_linetry_lt %>
    <%= form.number_field :t4_linetry_lt %>
  </div>

  <div class="field">
    <%= form.label :raw_material_lt %>
    <%= form.number_field :raw_material_lt %>
  </div>

  <div class="field">
    <%= form.label :go1_1_target %>
    <%= form.date_select :go1_1_target %>
  </div>

  <div class="field">
    <%= form.label :go1_1_actual %>
    <%= form.date_select :go1_1_actual %>
  </div>

  <div class="field">
    <%= form.label :go1_1_design_target %>
    <%= form.date_select :go1_1_design_target %>
  </div>

  <div class="field">
    <%= form.label :go1_1_correlated %>
    <%= form.date_select :go1_1_correlated %>
  </div>

  <div class="field">
    <%= form.label :go1_2_target %>
    <%= form.date_select :go1_2_target %>
  </div>

  <div class="field">
    <%= form.label :go1_2_actual %>
    <%= form.date_select :go1_2_actual %>
  </div>

  <div class="field">
    <%= form.label :go2_1_actual %>
    <%= form.date_select :go2_1_actual %>
  </div>

  <div class="field">
    <%= form.label :go2_2_target %>
    <%= form.date_select :go2_2_target %>
  </div>

  <div class="field">
    <%= form.label :go2_2_actual %>
    <%= form.text_field :go2_2_actual %>
  </div>

  <div class="field">
    <%= form.label :go2_2_design_target %>
    <%= form.date_select :go2_2_design_target %>
  </div>

  <div class="field">
    <%= form.label :go2_2_correlated %>
    <%= form.date_select :go2_2_correlated %>
  </div>

  <div class="field">
    <%= form.label :go2_3_actual %>
    <%= form.date_select :go2_3_actual %>
  </div>

  <div class="field">
    <%= form.label :go1_1_design_number %>
    <%= form.text_field :go1_1_design_number %>
  </div>

  <div class="field">
    <%= form.label :go1_2_design_number %>
    <%= form.text_field :go1_2_design_number %>
  </div>

  <div class="field">
    <%= form.label :go2_1_design_number %>
    <%= form.text_field :go2_1_design_number %>
  </div>

  <div class="field">
    <%= form.label :go2_2_design_number %>
    <%= form.text_field :go2_2_design_number %>
  </div>

  <div class="field">
    <%= form.label :go2_3_design_change %>
    <%= form.text_field :go2_3_design_change %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/toolings/edit.html.erb
<h1>Editing Tooling</h1>

<%= render 'form', tooling: @tooling %>

<%= link_to 'Show', @tooling %> |
<%= link_to 'Back', toolings_path %>

app/views/toolings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Toolings</h1>

<table>
  <thead>
    <tr>
      <th>Deliver to</th>
      <th>Part type</th>
      <th>Part level</th>
      <th>Commodity</th>
      <th>Tool source</th>
      <th>Go1 go2 lt</th>
      <th>Go2 t1 lt</th>
      <th>T1 t2 lt</th>
      <th>T2 t3 lt</th>
      <th>T3 t4 lt</th>
      <th>T4 linetry lt</th>
      <th>Raw material lt</th>
      <th>Go1 1 target</th>
      <th>Go1 1 actual</th>
      <th>Go1 1 design target</th>
      <th>Go1 1 correlated</th>
      <th>Go1 2 target</th>
      <th>Go1 2 actual</th>
      <th>Go2 1 actual</th>
      <th>Go2 2 target</th>
      <th>Go2 2 actual</th>
      <th>Go2 2 design target</th>
      <th>Go2 2 correlated</th>
      <th>Go2 3 actual</th>
      <th>Go1 1 design number</th>
      <th>Go1 2 design number</th>
      <th>Go2 1 design number</th>
      <th>Go2 2 design number</th>
      <th>Go2 3 design change</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @toolings.each do |tooling| %>
      <tr>
        <td><%= tooling.deliver_to %></td>
        <td><%= tooling.part_type %></td>
        <td><%= tooling.part_level %></td>
        <td><%= tooling.commodity %></td>
        <td><%= tooling.tool_source %></td>
        <td><%= tooling.go1_go2_lt %></td>
        <td><%= tooling.go2_t1_lt %></td>
        <td><%= tooling.t1_t2_lt %></td>
        <td><%= tooling.t2_t3_lt %></td>
        <td><%= tooling.t3_t4_lt %></td>
        <td><%= tooling.t4_linetry_lt %></td>
        <td><%= tooling.raw_material_lt %></td>
        <td><%= tooling.go1_1_target %></td>
        <td><%= tooling.go1_1_actual %></td>
        <td><%= tooling.go1_1_design_target %></td>
        <td><%= tooling.go1_1_correlated %></td>
        <td><%= tooling.go1_2_target %></td>
        <td><%= tooling.go1_2_actual %></td>
        <td><%= tooling.go2_1_actual %></td>
        <td><%= tooling.go2_2_target %></td>
        <td><%= tooling.go2_2_actual %></td>
        <td><%= tooling.go2_2_design_target %></td>
        <td><%= tooling.go2_2_correlated %></td>
        <td><%= tooling.go2_3_actual %></td>
        <td><%= tooling.go1_1_design_number %></td>
        <td><%= tooling.go1_2_design_number %></td>
        <td><%= tooling.go2_1_design_number %></td>
        <td><%= tooling.go2_2_design_number %></td>
        <td><%= tooling.go2_3_design_change %></td>
        <td><%= link_to 'Show', tooling %></td>
        <td><%= link_to 'Edit', edit_tooling_path(tooling) %></td>
        <td><%= link_to 'Destroy', tooling, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tooling', new_tooling_path %>

app/views/toolings/new.html.erb
<h1>New Tooling</h1>

<%= render 'form', tooling: @tooling %>

<%= link_to 'Back', toolings_path %>

app/views/toolings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Deliver to:</strong>
  <%= @tooling.deliver_to %>
</p>

<p>
  <strong>Part type:</strong>
  <%= @tooling.part_type %>
</p>

<p>
  <strong>Part level:</strong>
  <%= @tooling.part_level %>
</p>

<p>
  <strong>Commodity:</strong>
  <%= @tooling.commodity %>
</p>

<p>
  <strong>Tool source:</strong>
  <%= @tooling.tool_source %>
</p>

<p>
  <strong>Go1 go2 lt:</strong>
  <%= @tooling.go1_go2_lt %>
</p>

<p>
  <strong>Go2 t1 lt:</strong>
  <%= @tooling.go2_t1_lt %>
</p>

<p>
  <strong>T1 t2 lt:</strong>
  <%= @tooling.t1_t2_lt %>
</p>

<p>
  <strong>T2 t3 lt:</strong>
  <%= @tooling.t2_t3_lt %>
</p>

<p>
  <strong>T3 t4 lt:</strong>
  <%= @tooling.t3_t4_lt %>
</p>

<p>
  <strong>T4 linetry lt:</strong>
  <%= @tooling.t4_linetry_lt %>
</p>

<p>
  <strong>Raw material lt:</strong>
  <%= @tooling.raw_material_lt %>
</p>

<p>
  <strong>Go1 1 target:</strong>
  <%= @tooling.go1_1_target %>
</p>

<p>
  <strong>Go1 1 actual:</strong>
  <%= @tooling.go1_1_actual %>
</p>

<p>
  <strong>Go1 1 design target:</strong>
  <%= @tooling.go1_1_design_target %>
</p>

<p>
  <strong>Go1 1 correlated:</strong>
  <%= @tooling.go1_1_correlated %>
</p>

<p>
  <strong>Go1 2 target:</strong>
  <%= @tooling.go1_2_target %>
</p>

<p>
  <strong>Go1 2 actual:</strong>
  <%= @tooling.go1_2_actual %>
</p>

<p>
  <strong>Go2 1 actual:</strong>
  <%= @tooling.go2_1_actual %>
</p>

<p>
  <strong>Go2 2 target:</strong>
  <%= @tooling.go2_2_target %>
</p>

<p>
  <strong>Go2 2 actual:</strong>
  <%= @tooling.go2_2_actual %>
</p>

<p>
  <strong>Go2 2 design target:</strong>
  <%= @tooling.go2_2_design_target %>
</p>

<p>
  <strong>Go2 2 correlated:</strong>
  <%= @tooling.go2_2_correlated %>
</p>

<p>
  <strong>Go2 3 actual:</strong>
  <%= @tooling.go2_3_actual %>
</p>

<p>
  <strong>Go1 1 design number:</strong>
  <%= @tooling.go1_1_design_number %>
</p>

<p>
  <strong>Go1 2 design number:</strong>
  <%= @tooling.go1_2_design_number %>
</p>

<p>
  <strong>Go2 1 design number:</strong>
  <%= @tooling.go2_1_design_number %>
</p>

<p>
  <strong>Go2 2 design number:</strong>
  <%= @tooling.go2_2_design_number %>
</p>

<p>
  <strong>Go2 3 design change:</strong>
  <%= @tooling.go2_3_design_change %>
</p>

<%= link_to 'Edit', edit_tooling_path(@tooling) %> |
<%= link_to 'Back', toolings_path %>