config/routes.rb
Rails.application.routes.draw do
  resources :toolings
  resources :parts
  devise_for :supplier_users
  devise_for :honda_users
  resources :events
  resources :projects
  resources :maker_layouts
  resources :plants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/cost.rb
class Cost < ApplicationRecord
end

app/models/design_confirm.rb
class DesignConfirm < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/honda_user.rb
class HondaUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/maker_layout.rb
class MakerLayout < ApplicationRecord
end

app/models/maturation_confirm.rb
class MaturationConfirm < ApplicationRecord
end

app/models/part.rb
class Part < ApplicationRecord
end

app/models/plant.rb
class Plant < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/supplier_user.rb
class SupplierUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/tooling.rb
class Tooling < ApplicationRecord
end

app/controllers/maker_layouts_controller.rb
class MakerLayoutsController < ApplicationController
  before_action :set_maker_layout, only: [:show, :edit, :update, :destroy]

  # GET /maker_layouts
  # GET /maker_layouts.json
  def index
    @maker_layouts = MakerLayout.all
  end

  # GET /maker_layouts/1
  # GET /maker_layouts/1.json
  def show
  end

  # GET /maker_layouts/new
  def new
    @maker_layout = MakerLayout.new
  end

  # GET /maker_layouts/1/edit
  def edit
  end

  # POST /maker_layouts
  # POST /maker_layouts.json
  def create
    @maker_layout = MakerLayout.new(maker_layout_params)

    respond_to do |format|
      if @maker_layout.save
        format.html { redirect_to @maker_layout, notice: 'Maker layout was successfully created.' }
        format.json { render :show, status: :created, location: @maker_layout }
      else
        format.html { render :new }
        format.json { render json: @maker_layout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maker_layouts/1
  # PATCH/PUT /maker_layouts/1.json
  def update
    respond_to do |format|
      if @maker_layout.update(maker_layout_params)
        format.html { redirect_to @maker_layout, notice: 'Maker layout was successfully updated.' }
        format.json { render :show, status: :ok, location: @maker_layout }
      else
        format.html { render :edit }
        format.json { render json: @maker_layout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maker_layouts/1
  # DELETE /maker_layouts/1.json
  def destroy
    @maker_layout.destroy
    respond_to do |format|
      format.html { redirect_to maker_layouts_url, notice: 'Maker layout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maker_layout
      @maker_layout = MakerLayout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maker_layout_params
      params.require(:maker_layout).permit(:supplier_number, :location_code, :address, :city, :state, :country)
    end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:part_number, :part_name, :process_1, :process_2, :process_3, :color, :makerlayout_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/maker_layouts_helper.rb
module MakerLayoutsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/toolings_helper.rb
module ToolingsHelper
end

app/views/maker_layouts/_form.html.erb
<%= form_with(model: maker_layout, local: true) do |form| %>
  <% if maker_layout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(maker_layout.errors.count, "error") %> prohibited this maker_layout from being saved:</h2>

      <ul>
      <% maker_layout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :supplier_number %>
    <%= form.number_field :supplier_number %>
  </div>

  <div class="field">
    <%= form.label :location_code %>
    <%= form.number_field :location_code %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/maker_layouts/edit.html.erb
<h1>Editing Maker Layout</h1>

<%= render 'form', maker_layout: @maker_layout %>

<%= link_to 'Show', @maker_layout %> |
<%= link_to 'Back', maker_layouts_path %>

app/views/maker_layouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Maker Layouts</h1>

<table>
  <thead>
    <tr>
      <th>Supplier number</th>
      <th>Location code</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maker_layouts.each do |maker_layout| %>
      <tr>
        <td><%= maker_layout.supplier_number %></td>
        <td><%= maker_layout.location_code %></td>
        <td><%= maker_layout.address %></td>
        <td><%= maker_layout.city %></td>
        <td><%= maker_layout.state %></td>
        <td><%= maker_layout.country %></td>
        <td><%= link_to 'Show', maker_layout %></td>
        <td><%= link_to 'Edit', edit_maker_layout_path(maker_layout) %></td>
        <td><%= link_to 'Destroy', maker_layout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Maker Layout', new_maker_layout_path %>

app/views/maker_layouts/new.html.erb
<h1>New Maker Layout</h1>

<%= render 'form', maker_layout: @maker_layout %>

<%= link_to 'Back', maker_layouts_path %>

app/views/maker_layouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Supplier number:</strong>
  <%= @maker_layout.supplier_number %>
</p>

<p>
  <strong>Location code:</strong>
  <%= @maker_layout.location_code %>
</p>

<p>
  <strong>Address:</strong>
  <%= @maker_layout.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @maker_layout.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @maker_layout.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @maker_layout.country %>
</p>

<%= link_to 'Edit', edit_maker_layout_path(@maker_layout) %> |
<%= link_to 'Back', maker_layouts_path %>