config/routes.rb
Rails.application.routes.draw do
  resources :toolings
  resources :parts
  devise_for :supplier_users
  devise_for :honda_users
  resources :events
  resources :projects
  resources :maker_layouts
  resources :plants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/cost.rb
class Cost < ApplicationRecord
end

app/models/design_confirm.rb
class DesignConfirm < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/honda_user.rb
class HondaUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/maker_layout.rb
class MakerLayout < ApplicationRecord
end

app/models/maturation_confirm.rb
class MaturationConfirm < ApplicationRecord
end

app/models/part.rb
class Part < ApplicationRecord
end

app/models/plant.rb
class Plant < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/supplier_user.rb
class SupplierUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/tooling.rb
class Tooling < ApplicationRecord
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event_name, :line, :weld_dsps_delivery, :weld_delivery, :trim_dsps_delivery, :trim_delivery, :tier3_delivery, :project_id, :plant_id, :stamp_weld_mat_target, :plastic_mat_target, :comp_elect_assy_mat_target, :wire_harness_mat_target, :cast_machine_mat_target, :pipe_tube_mat_target, :rubber_metal_mat_target)
    end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:part_number, :part_name, :process_1, :process_2, :process_3, :color, :makerlayout_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/maker_layouts_helper.rb
module MakerLayoutsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/toolings_helper.rb
module ToolingsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :event_name %>
    <%= form.text_field :event_name %>
  </div>

  <div class="field">
    <%= form.label :line %>
    <%= form.number_field :line %>
  </div>

  <div class="field">
    <%= form.label :weld_dsps_delivery %>
    <%= form.date_select :weld_dsps_delivery %>
  </div>

  <div class="field">
    <%= form.label :weld_delivery %>
    <%= form.date_select :weld_delivery %>
  </div>

  <div class="field">
    <%= form.label :trim_dsps_delivery %>
    <%= form.date_select :trim_dsps_delivery %>
  </div>

  <div class="field">
    <%= form.label :trim_delivery %>
    <%= form.date_select :trim_delivery %>
  </div>

  <div class="field">
    <%= form.label :tier3_delivery %>
    <%= form.date_select :tier3_delivery %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.number_field :project_id %>
  </div>

  <div class="field">
    <%= form.label :plant_id %>
    <%= form.number_field :plant_id %>
  </div>

  <div class="field">
    <%= form.label :stamp_weld_mat_target %>
    <%= form.text_field :stamp_weld_mat_target %>
  </div>

  <div class="field">
    <%= form.label :plastic_mat_target %>
    <%= form.text_field :plastic_mat_target %>
  </div>

  <div class="field">
    <%= form.label :comp_elect_assy_mat_target %>
    <%= form.text_field :comp_elect_assy_mat_target %>
  </div>

  <div class="field">
    <%= form.label :wire_harness_mat_target %>
    <%= form.text_field :wire_harness_mat_target %>
  </div>

  <div class="field">
    <%= form.label :cast_machine_mat_target %>
    <%= form.text_field :cast_machine_mat_target %>
  </div>

  <div class="field">
    <%= form.label :pipe_tube_mat_target %>
    <%= form.text_field :pipe_tube_mat_target %>
  </div>

  <div class="field">
    <%= form.label :rubber_metal_mat_target %>
    <%= form.text_field :rubber_metal_mat_target %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Event name</th>
      <th>Line</th>
      <th>Weld dsps delivery</th>
      <th>Weld delivery</th>
      <th>Trim dsps delivery</th>
      <th>Trim delivery</th>
      <th>Tier3 delivery</th>
      <th>Project</th>
      <th>Plant</th>
      <th>Stamp weld mat target</th>
      <th>Plastic mat target</th>
      <th>Comp elect assy mat target</th>
      <th>Wire harness mat target</th>
      <th>Cast machine mat target</th>
      <th>Pipe tube mat target</th>
      <th>Rubber metal mat target</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.event_name %></td>
        <td><%= event.line %></td>
        <td><%= event.weld_dsps_delivery %></td>
        <td><%= event.weld_delivery %></td>
        <td><%= event.trim_dsps_delivery %></td>
        <td><%= event.trim_delivery %></td>
        <td><%= event.tier3_delivery %></td>
        <td><%= event.project_id %></td>
        <td><%= event.plant_id %></td>
        <td><%= event.stamp_weld_mat_target %></td>
        <td><%= event.plastic_mat_target %></td>
        <td><%= event.comp_elect_assy_mat_target %></td>
        <td><%= event.wire_harness_mat_target %></td>
        <td><%= event.cast_machine_mat_target %></td>
        <td><%= event.pipe_tube_mat_target %></td>
        <td><%= event.rubber_metal_mat_target %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event name:</strong>
  <%= @event.event_name %>
</p>

<p>
  <strong>Line:</strong>
  <%= @event.line %>
</p>

<p>
  <strong>Weld dsps delivery:</strong>
  <%= @event.weld_dsps_delivery %>
</p>

<p>
  <strong>Weld delivery:</strong>
  <%= @event.weld_delivery %>
</p>

<p>
  <strong>Trim dsps delivery:</strong>
  <%= @event.trim_dsps_delivery %>
</p>

<p>
  <strong>Trim delivery:</strong>
  <%= @event.trim_delivery %>
</p>

<p>
  <strong>Tier3 delivery:</strong>
  <%= @event.tier3_delivery %>
</p>

<p>
  <strong>Project:</strong>
  <%= @event.project_id %>
</p>

<p>
  <strong>Plant:</strong>
  <%= @event.plant_id %>
</p>

<p>
  <strong>Stamp weld mat target:</strong>
  <%= @event.stamp_weld_mat_target %>
</p>

<p>
  <strong>Plastic mat target:</strong>
  <%= @event.plastic_mat_target %>
</p>

<p>
  <strong>Comp elect assy mat target:</strong>
  <%= @event.comp_elect_assy_mat_target %>
</p>

<p>
  <strong>Wire harness mat target:</strong>
  <%= @event.wire_harness_mat_target %>
</p>

<p>
  <strong>Cast machine mat target:</strong>
  <%= @event.cast_machine_mat_target %>
</p>

<p>
  <strong>Pipe tube mat target:</strong>
  <%= @event.pipe_tube_mat_target %>
</p>

<p>
  <strong>Rubber metal mat target:</strong>
  <%= @event.rubber_metal_mat_target %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/parts/_form.html.erb
<%= form_with(model: part, local: true) do |form| %>
  <% if part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
      <% part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :part_number %>
    <%= form.text_field :part_number %>
  </div>

  <div class="field">
    <%= form.label :part_name %>
    <%= form.text_field :part_name %>
  </div>

  <div class="field">
    <%= form.label :process_1 %>
    <%= form.text_field :process_1 %>
  </div>

  <div class="field">
    <%= form.label :process_2 %>
    <%= form.text_field :process_2 %>
  </div>

  <div class="field">
    <%= form.label :process_3 %>
    <%= form.text_field :process_3 %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.check_box :color %>
  </div>

  <div class="field">
    <%= form.label :makerlayout_id %>
    <%= form.number_field :makerlayout_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parts/edit.html.erb
<h1>Editing Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

app/views/parts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parts</h1>

<table>
  <thead>
    <tr>
      <th>Part number</th>
      <th>Part name</th>
      <th>Process 1</th>
      <th>Process 2</th>
      <th>Process 3</th>
      <th>Color</th>
      <th>Makerlayout</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parts.each do |part| %>
      <tr>
        <td><%= part.part_number %></td>
        <td><%= part.part_name %></td>
        <td><%= part.process_1 %></td>
        <td><%= part.process_2 %></td>
        <td><%= part.process_3 %></td>
        <td><%= part.color %></td>
        <td><%= part.makerlayout_id %></td>
        <td><%= link_to 'Show', part %></td>
        <td><%= link_to 'Edit', edit_part_path(part) %></td>
        <td><%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Part', new_part_path %>

app/views/parts/new.html.erb
<h1>New Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Back', parts_path %>

app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Part number:</strong>
  <%= @part.part_number %>
</p>

<p>
  <strong>Part name:</strong>
  <%= @part.part_name %>
</p>

<p>
  <strong>Process 1:</strong>
  <%= @part.process_1 %>
</p>

<p>
  <strong>Process 2:</strong>
  <%= @part.process_2 %>
</p>

<p>
  <strong>Process 3:</strong>
  <%= @part.process_3 %>
</p>

<p>
  <strong>Color:</strong>
  <%= @part.color %>
</p>

<p>
  <strong>Makerlayout:</strong>
  <%= @part.makerlayout_id %>
</p>

<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>